# num=[1,2,3,4,5]
# print("orginal list:",num)
# num.append(7)
# print("after append:",num)
# num.insert(0,6)
# print("after Insert:",num)
# num.remove(2)
# print("after remove:",num)
# num.sort()
# print("sort:",num)
# num.reverse()
# print("reverse:",num)
# print("length of list:",len(num))
# print("first element:",num[0])
# print("last element:",num[-1])
num=input("Enter items:").split()
print("your list is:",num)