# a=10
# b=0o10
# c=0x10
# d=0b10
# print(oct(a))
# print(oct(b))
# print(oct(c))
# print(oct(d))
# print(bin(d))

# a=24
# b=0o24
# c=0x24
# d=0b10
# print(bin(a))
# print(bin(b))
# print(bin(c))
# print(bin(d))
# print(oct(a))
# print(oct(b))
# print(oct(c))
# print(oct(d))
# print(hex(a))
# print(hex(b))
# print(hex(c))
# print(hex(d))

# a=82
# b=0o115
# c=0x3ca
# d=0b11000
# print(bin(a))
# print(bin(b))
# print(bin(c))
# print(bin(d))
# print(oct(a))
# print(oct(b))
# print(oct(c))
# print(oct(d))
# print(hex(a))
# print(hex(b))
# print(hex(c))
# print(hex(d))